export type BookingStatus =
  | 'REQUESTED'
  | 'CONFIRMED'
  | 'DRIVER_ASSIGNED'
  | 'IN_TRANSIT'
  | 'COMPLETED'
  | 'CANCELLED';

export interface BookingRecord {
  id: string;
  bookingRef: string;
  idempotencyKey?: string;
  customerName: string;
  customerPhone: string;
  customerEmail?: string;
  serviceType: string;
  subType: string;
  pickupLocation: string;
  dropoffLocation: string;
  travelDate: string;
  pickupTime: string;
  vehicleCategory: string;
  vehicleName: string;
  estimatedDistanceKm: number;
  totalFare: number;
  paymentMethod: string;
  status: BookingStatus;
  otp: string;
  assignedDriver?: {
    name: string;
    phone: string;
    vehicleNumber: string;
    rating: number;
    tripsCompleted: number;
  };
  auditLog: {
    status: BookingStatus;
    timestamp: string;
    note: string;
  }[];
  createdAt: string;
  updatedAt: string;
}

// In-memory high speed state store with index by bookingRef and idempotencyKey
class BookingEngine {
  private bookingsByRef: Map<string, BookingRecord> = new Map();
  private idempotencyIndex: Map<string, string> = new Map(); // idempotencyKey -> bookingRef

  constructor() {
    // Seed initial operational bookings for real-time tracking
    this.seedDemoBookings();
  }

  private seedDemoBookings() {
    const demoRef = 'WAL-92841';
    this.bookingsByRef.set(demoRef, {
      id: 'book_demo_1',
      bookingRef: demoRef,
      customerName: 'Suresh Kumar',
      customerPhone: '+91 98480 22334',
      customerEmail: 'suresh.k@gmail.com',
      serviceType: 'airport',
      subType: 'pickup',
      pickupLocation: 'Visakhapatnam Airport (VTZ)',
      dropoffLocation: 'Novotel Hotel, Beach Road, Vizag',
      travelDate: new Date().toISOString().split('T')[0],
      pickupTime: '14:30',
      vehicleCategory: 'sedan',
      vehicleName: 'Swift Dzire Premium',
      estimatedDistanceKm: 16,
      totalFare: 800,
      paymentMethod: 'Cash to Driver',
      status: 'DRIVER_ASSIGNED',
      otp: '7492',
      assignedDriver: {
        name: 'Ravi Teja',
        phone: '+91 98491 55667',
        vehicleNumber: 'AP 31 TV 4829',
        rating: 4.9,
        tripsCompleted: 1420,
      },
      auditLog: [
        { status: 'REQUESTED', timestamp: new Date(Date.now() - 3600000).toISOString(), note: 'Booking submitted via Web App' },
        { status: 'CONFIRMED', timestamp: new Date(Date.now() - 3500000).toISOString(), note: 'Fare locked and guaranteed' },
        { status: 'DRIVER_ASSIGNED', timestamp: new Date(Date.now() - 3000000).toISOString(), note: 'Driver Ravi Teja dispatched' },
      ],
      createdAt: new Date(Date.now() - 3600000).toISOString(),
      updatedAt: new Date(Date.now() - 3000000).toISOString(),
    });
  }

  public createBooking(payload: Omit<BookingRecord, 'id' | 'otp' | 'status' | 'auditLog' | 'createdAt' | 'updatedAt'> & { idempotencyKey?: string }): BookingRecord {
    // 1. Idempotency Check
    if (payload.idempotencyKey && this.idempotencyIndex.has(payload.idempotencyKey)) {
      const existingRef = this.idempotencyIndex.get(payload.idempotencyKey)!;
      const existing = this.bookingsByRef.get(existingRef);
      if (existing) return existing;
    }

    const bookingRef = payload.bookingRef || `WAL-${Math.floor(10000 + Math.random() * 90000)}`;
    const otp = Math.floor(1000 + Math.random() * 9000).toString();
    const now = new Date().toISOString();

    const record: BookingRecord = {
      ...payload,
      id: `bk_${Date.now()}_${Math.random().toString(36).substring(2, 7)}`,
      bookingRef,
      status: 'CONFIRMED',
      otp,
      assignedDriver: {
        name: 'K. Venkatesh Rao',
        phone: '+91 98485 12049',
        vehicleNumber: 'AP 31 TH 8842',
        rating: 4.88,
        tripsCompleted: 890,
      },
      auditLog: [
        {
          status: 'REQUESTED',
          timestamp: now,
          note: 'Booking successfully generated by Waltair High-Availability Booking Engine',
        },
        {
          status: 'CONFIRMED',
          timestamp: now,
          note: 'Tariff confirmed with zero surge pricing guarantee',
        },
      ],
      createdAt: now,
      updatedAt: now,
    };

    this.bookingsByRef.set(bookingRef, record);
    if (payload.idempotencyKey) {
      this.idempotencyIndex.set(payload.idempotencyKey, bookingRef);
    }

    return record;
  }

  public getBookingByRef(bookingRef: string): BookingRecord | null {
    return this.bookingsByRef.get(bookingRef.toUpperCase()) || null;
  }

  public updateBookingStatus(bookingRef: string, newStatus: BookingStatus, note: string): BookingRecord | null {
    const record = this.bookingsByRef.get(bookingRef.toUpperCase());
    if (!record) return null;

    // State machine transition validator
    const validTransitions: Record<BookingStatus, BookingStatus[]> = {
      REQUESTED: ['CONFIRMED', 'CANCELLED'],
      CONFIRMED: ['DRIVER_ASSIGNED', 'CANCELLED'],
      DRIVER_ASSIGNED: ['IN_TRANSIT', 'CANCELLED'],
      IN_TRANSIT: ['COMPLETED', 'CANCELLED'],
      COMPLETED: [],
      CANCELLED: [],
    };

    const allowed = validTransitions[record.status] || [];
    if (!allowed.includes(newStatus)) {
      throw new Error(`Invalid state transition from ${record.status} to ${newStatus}`);
    }

    const now = new Date().toISOString();
    record.status = newStatus;
    record.updatedAt = now;
    record.auditLog.push({
      status: newStatus,
      timestamp: now,
      note,
    });

    return record;
  }

  public listRecentBookings(limit: number = 20): BookingRecord[] {
    return Array.from(this.bookingsByRef.values())
      .sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime())
      .slice(0, limit);
  }
}

export const bookingEngine = new BookingEngine();
